name: Github Actions CI
run-name: CI for Github Actions
on: [push]
jobs:
    Gitlab-Actions-CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "$(date) - Starting the Gitlab Actions CI workflow..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: List files
              run: ls -la

    Test:
        runs-on: ubuntu-latest
        needs: [Gitlab-Actions-CI]
        steps:
            - run: echo "$(date) - Starting the tests..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                cache: false
                go-version: '>=1.20'

            - name: Run tests
              run: go test ./...

    Build:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        needs: [Test]
        steps:
            - run: echo "$(date) - Starting the build..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                cache: false
                go-version: '>=1.20'

            - name: Extract version from tag
              id: get_version
              run: |
                echo "APP_VERSION=$(echo ${{ github.ref }} | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

            - name: Show version
              run: |
                echo "Version is ${{ env.APP_VERSION }}"

            - name: Build application
              run: go build -ldflags="-X 'main.version=${{ env.APP_VERSION }}'" -o hello-actions ./cmd/main.go

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello-actions
                path: hello-actions

            - name: List files
              run: ls -la

    Deployment:
        runs-on: [self-hosted]
        needs: [Build]
        env:
          SERVER_PWD: ${{ secrets.SERVER_PWD }}
        steps:
            - run: echo "$(date) - Starting the deployment..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy application
              uses: actions/download-artifact@v4
              with:
                name: hello-actions

            - name: Move application and service to /usr/local/bin
              shell: bash
              run: |
                echo "$SERVER_PWD" | sudo -S chmod +x hello-actions
                echo "$SERVER_PWD" | sudo -S mv hello-actions /usr/bin/hello-actions
                echo "$SERVER_PWD" | sudo -S mv hello-actions.service /etc/systemd/system/hello-actions.service

            - name: Running an application service
              shell: bash
              run: |
                echo "$SERVER_PWD" | sudo -S systemctl enable hello-actions.service
                echo "$SERVER_PWD" | sudo -S systemctl start hello-actions.service

            - name: Current user
              run: whoami

            - name: Current location
              run: pwd

            - name: Notify deployment
              run: echo "Deployment completed successfully!"

            - run: echo "$(date) - Gitlab Actions CI workflow completed."