name: Github Actions CI
run-name: CI for Github Actions
on: [push]
jobs:
    Gitlab-Actions-CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "$(date) - Starting the Gitlab Actions CI workflow..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: List files
              run: ls -la

    Test:
        runs-on: ubuntu-latest
        needs: [Gitlab-Actions-CI]
        steps:
            - run: echo "$(date) - Starting the tests..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                cache: false
                go-version: '>=1.20'

            - name: Run tests
              run: go test ./...

    Build:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        needs: [Test]
        steps:
            - run: echo "$(date) - Starting the build..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                cache: false
                go-version: '>=1.20'

            - name: Extract version from tag
              id: get_version
              run: |
                echo "APP_VERSION=$(echo ${{ github.ref }} | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

            - name: Show version
              run: |
                echo "Version is ${{ env.APP_VERSION }}"

            - name: Registry authentication
              run: echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                push: true
                build-args: |
                  VERSION=${{ env.APP_VERSION }}
                tags: |
                  ghcr.io/${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:${{ env.APP_VERSION }}
                  ghcr.io/${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest

            - name: List files
              run: ls -la

    Deployment:
        runs-on: [self-hosted]
        needs: [Build]
        env:
          SERVER_PWD: ${{ secrets.SERVER_PWD }}
        steps:
            - run: echo "$(date) - Starting the deployment..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Registry authentication
              run: echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
            
            - name: Pull image
              run: echo ${{ secrets.SERVER_PWD }} | sudo -S docker pull ghcr.io/${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest

            - name: Run container
              run: |
                echo ${{ secrets.SERVER_PWD }} | sudo -S docker run -d --name ${{ secrets.IMAGE_NAME }} -p ${{ secrets.EXPOSE_APP_PORT }}:${{ secrets.APP_PORT }} ghcr.io/${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest -p ${{ secrets.APP_PORT }}

            - name: Current user
              run: whoami

            - name: Current location
              run: pwd

            - name: Notify deployment
              run: echo "Deployment completed successfully!"

            - run: echo "$(date) - Gitlab Actions CI workflow completed."