name: Gitlab Actions CI
run-name: CI for Gitlab Actions
on: [push]
jobs:
    Gitlab-Actions-CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "$(date) - Starting the Gitlab Actions CI workflow..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: List files
              run: ls -la

    Test:
        runs-on: ubuntu-latest
        needs: [Gitlab-Actions-CI]
        steps:
            - run: echo "$(date) - Starting the tests..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                cache: false
                go-version: '>=1.20'

            - name: Run tests
              run: go test ./...

    Deployment:
        runs-on: [self-hosted]
        needs: [Test]
        steps:
            - run: echo "$(date) - Starting the deployment..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy application
              run: echo "Deploying the application..."

            - name: Current user
              run: whoami

            - name: Current location
              run: pwd

            - name: Notify deployment
              run: echo "Deployment completed successfully!"

            - run: echo "$(date) - Gitlab Actions CI workflow completed."