name: Gitlab Actions CI
run-name: CI for Gitlab Actions
on: [push]
jobs:
    Gitlab-Actions-CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "$(date) - Starting the Gitlab Actions CI workflow..."

            - name: Checkout code
              uses: actions/checkout@v3

            - name: List files
              run: ls -la
